name: Android
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        newArchEnabled: [false, true]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Set up JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install npm dependencies
        run: yarn --frozen-lockfile
        shell: bash
      - name: Build Android test app
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2
        with:
          gradle-version: wrapper
          arguments: -PnewArchEnabled=${{matrix.newArchEnabled}} --no-daemon clean build check test
          build-root-directory: example/android
    timeout-minutes: 60
