name: Android
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        newArchEnabled: [false, true]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: 'yarn'
      - name: Set up JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          distribution: temurin
          java-version: 17
      - name: Install npm dependencies
        run: yarn --frozen-lockfile
        shell: bash
      - name: Build Android test app
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0
        with:
          gradle-version: wrapper
          arguments: -PnewArchEnabled=${{matrix.newArchEnabled}} --no-daemon clean build check test
          build-root-directory: example/android
    timeout-minutes: 60
